### ISSUE TITLE
Add S3 Access Keys

### ISSUE THREAD

**Issue by leovigna** [orangain/scrapy-s3pipeline#1]
Unable to use AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY in settings.py.
This would be useful when running the spider on scrapyd since there is not .aws/config file by default.

Suggested edit: pipelines.py line 33:
`self.s3 = boto3.client('s3',
            aws_access_key_id=settings.get('AWS_ACCESS_KEY_ID'),
            aws_secret_access_key=settings.get('AWS_SECRET_ACCESS_KEY'))`

**Comment by orangain** [comment]
@lion9901 Thank you for the suggestion! I've just released new version of scrapy-s3pipeline that supports `AWS_*` settings. Please give it a try.

**Comment by ramisvik** [comment]
Hi @orangain. I need to encrypt my files using KMS. How to go about it?
