### ISSUE TITLE
Json object are not delimited and not within array using JsonLinesItemExporter

### ISSUE THREAD

**Issue by chipzzz** [orangain/scrapy-s3pipeline#9]
Using scrapy-s3pipeline, a but json items are not delimited or within array

see https://github.com/scrapy/scrapy/issues/4960

**Comment by orangain** [comment]
@chipzzz Thank you for reporting issue! The new version of scrapy-s3pipeline 0.7.0 supports JSON array format. Please try it from [PyPI](https://pypi.org/project/scrapy-s3pipeline/).
